const data = [
    [
      {
        id: 1,
        name: 'Аист белый',
        nameLatin: 'Ciconia ciconia',
        band: 'Аистообразные',
        bandLatin: 'Ciconiiformes',
        family: 'Аистовые',
        familyLatin: 'Ciconiidae',
        description: 'Гнездящийся перелетный и транзитно мигрирующий вид. Территория Беларуси условно разделена на 3 региона с различной плотностью гнездования.',
        weight: 'самцы 2,9-3,6 кг, самки 2,9-3,1 кг',
        length: '97-110 см',
        wingspan: '200-220 см',
        image: 'https://live.staticflickr.com/65535/48282626752_4c121a8c7a.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/LNDCYHUSPR/XC527477-12%20feb.%2013.35%20cig%C3%BCe%C3%B1as.mp3',
      },
      {
        id: 2,
        name: 'Выпь',
        nameLatin: 'Botaurus stellaris',
        band: 'Аистообразные',
        bandLatin: 'Ciconiiformes',
        family: 'Цаплевые',
        familyLatin: 'Ardeidae',
        description: 'Немногочисленный гнездящийся, перелетный, транзитно мигрирующий и единично зимующий вид, но местами, особенно в Полесье, достаточно обычный вид.',
        weight: 'самцы 0,96-1,7 кг, самки 0,86-1,1 кг',
        length: '72-77 см',
        wingspan: '105-120 см',
        image: '',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/VOLIQOYWKG/XC522467-180505_04_roerdomp_%20belarus%20fishfarm_.mp3',
      },
      {
        id: 3,
        name: 'Каравайка',
        nameLatin: 'Plegadis falcinellus',
        band: 'Аистообразные',
        bandLatin: 'Ciconiiformes',
        family: 'Ибисовые',
        familyLatin: 'Threskiornithidae',
        description: 'Очень редкий случайно залетный вид, известны всего несколько регистраций: Гомельская область (Буда-Кошелевский, Житковичский, Светлогорский районы).',
        weight: '530-780 г (оба пола)',
        length: '51-66 см',
        wingspan: '80-105 см',
        image: '',
        audio: '',
      },
      {
        id: 4,
        name: 'Кваква',
        nameLatin: 'Nycticorax nycticorax',
        band: 'Аистообразные',
        bandLatin: 'Ciconiiformes',
        family: 'Цаплевые',
        familyLatin: 'Ardeidae',
        description: 'Очень редкий нерегулярно гнездящийся перелетный вид. Впервые несколько гнезд кваквы найдены в большой колонии серых цапель на Припяти у устья р. Лань в Лунинецком р-не.',
        weight: '550-650 г (оба пола)',
        length: '58-65 см',
        wingspan: '95-112 см',
        image: '',
        audio: '',
      },
      {
        id: 5,
        name: 'Колпица',
        nameLatin: 'Platalea leucorodia',
        band: 'Аистообразные',
        bandLatin: 'Ciconiiformes',
        family: 'Ибисовые',
        familyLatin: 'Threskiornithidae',
        description: 'Очень редкий случайно залетный вид. По данным орнитологов XIX века, колпица в то время гнездилась в бассейне р. Припять. Небольшие стайки этого вида регистрировались на водоемах Полесья еще в 1903 и 1910 гг.',
        weight: '1,5-1,8 кг (оба пола)',
        length: '75-90 см',
        wingspan: '115-145 см',
        image: '',
        audio: '',
      },
      {
        id: 6,
        name: 'Цапля серая',
        nameLatin: 'Ardea cinerea',
        band: 'Аистообразные',
        bandLatin: 'Ciconiiformes',
        family: 'Цаплевые',
        familyLatin: 'Ardeidae',
        description: 'Обычный гнездящийся, перелетный, транзитно мигрирующий и в небольшом числе зимующий вид. Наиболее известная из наших цапель, но чаще встречается в бассейне р. Припять и в Поозерье.',
        weight: 'самцы 1,3-2,25 кг, самки 1,1-2,1 кг',
        length: '92-99 см',
        wingspan: '145-170 см',
        image: '',
        audio: '',
      }
    ],
    [
      {
        id: 1,
        name: 'Гоголь',
        nameLatin: 'Bucephala clangula',
        band: 'Гусеобразные',
        bandLatin: 'Anseriformes',
        family: 'Утиные',
        familyLatin: 'Anatidae',
        description: 'В Беларуси – малочисленный гнездящийся перелетный, транзитно мигрирующий и в небольшом количестве зимующий вид, встречается преимущественно в северной части.',
        weight: 'самцы 570-900 г, самки 550-810 г',
        length: '32-36 см',
        wingspan: '62-69 см',
        image: '',
        audio: '',
      },
      {
        id: 2,
        name: 'Гуменник',
        nameLatin: 'Anser fabalis',
        band: 'Гусеобразные',
        bandLatin: 'Anseriformes',
        family: 'Утиные',
        familyLatin: 'Anatidae',
        description: 'В Беларуси среди транзитно мигрирующих гусей занимает второе место по численности. Встречается на осеннем и весеннем пролетах, единичные особи отмечались и на зимовке.',
        weight: 'самцы 2,7-3,7 кг, самки 1,7-2,6 кг',
        length: '61-90 см',
        wingspan: '152-166 см',
        image: '',
        audio: '',
      },
      {
        id: 3,
        name: 'Гусь серый',
        nameLatin: 'Anser anser',
        band: 'Гусеобразные',
        bandLatin: 'Anseriformes',
        family: 'Утиные',
        familyLatin: 'Anatidae',
        description: 'Редкий гнездящийся, малочисленный пролетный и очень редко зимующий вид. Гнездится спорадически. В настоящее время гнездится преимущественно в южной, западной и северо-западной части республики.',
        weight: 'самцы 3,1-5,2 кг, самки 3,0-4,6 кг',
        length: '76-92 см',
        wingspan: '143-174 см',
        image: '',
        audio: '',
      },
      {
        id: 4,
        name: 'Кряква',
        nameLatin: 'Anas platyrhynchos',
        band: 'Гусеобразные',
        bandLatin: 'Anseriformes',
        family: 'Утиные',
        familyLatin: 'Anatidae',
        description: 'Гнездящийся, перелетный, транзитно мигрирующий и нередко зимующий вид. Самая обычная в Беларуси утка, является традиционным объектом спортивной охоты.',
        weight: '840-1400 г (оба пола)',
        length: '51-63 см',
        wingspan: '82-100 см',
        image: '',
        audio: '',
      },
      {
        id: 5,
        name: 'Лебедь-шипун',
        nameLatin: 'Cygnus olor',
        band: 'Гусеобразные',
        bandLatin: 'Anseriformes',
        family: 'Утиные',
        familyLatin: 'Anatidae',
        description: 'Малочисленный гнездящийся, перелетный, транзитно мигрирующий, нередко зимующий вид. Исконный обитатель наших водоемов, лебедь шипун был полностью истреблен к началу XIX столетия и до 80-х годов XX века практически отсутствовал в нашей фауне.',
        weight: 'самцы 6,45-13,0 кг, самки 5,7-8,0 кг',
        length: '144-187 см',
        wingspan: '194-228 см',
        image: '',
        audio: '',
      },
      {
        id: 6,
        name: 'Шилохвость',
        nameLatin: 'Anas acuta',
        band: 'Гусеобразные',
        bandLatin: 'Anseriformes',
        family: 'Утиные',
        familyLatin: 'Anatidae',
        description: 'Изредка гнездящаяся, более обычная во время миграций и крайне редко зимующая утка. Единичные находки на гнездовании известны во всех областях.',
        weight: 'самцы 740-1050 г, самки 640-880 г',
        length: 'самцы 61-76 см, самки 51-60 см',
        wingspan: '84-91 см',
        image: '',
        audio: '',
      }
    ],
    [
      {
        id: 1,
        name: 'Глухарь',
        nameLatin: 'Tetrao urogallus',
        band: 'Курообразные',
        bandLatin: 'Galliiformes',
        family: 'Тетеревиные',
        familyLatin: 'Tetraonidae',
        description: 'Малочисленный гнездящийся оседлый вид. Встречается в лесах на всей территории за исключением крайнего юго-запада Брестской области и юго-востока Гомельской области.',
        weight: 'самцы 3,5-6,2 кг, самки 1,5-2,2 кг',
        length: '40-64 см',
        wingspan: '96-130 см',
        image: '',
        audio: '',
      },
      {
        id: 2,
        name: 'Перепел',
        nameLatin: 'Coturnix coturnix',
        band: 'Курообразные',
        bandLatin: 'Galliiformes',
        family: 'Фазановые',
        familyLatin: 'Phasianidae',
        description: 'Немногочисленный гнездящийся, перелетный и транзитно мигрирующий вид (единственная из отряда перелетная птица в нашей фауне). Распространен на всей территории, но не равномерно.',
        weight: 'самцы 76-106 г, самки 75-96 г',
        length: '16-21,5 см',
        wingspan: '33-39 см',
        image: '',
        audio: '',
      },
      {
        id: 3,
        name: 'Куропатка серая',
        nameLatin: 'Perdix perdix',
        band: 'Курообразные',
        bandLatin: 'Galliiformes',
        family: 'Фазановые',
        familyLatin: 'Phasianidae',
        description: 'Обычная гнездящаяся птица, ведет оседлый образ жизни. Распространение широкое, но неравномерно, в зависимости от качества угодий.',
        weight: '300-500 г (оба пола)',
        length: '15,5-31,5 см',
        wingspan: '48-55 см',
        image: '',
        audio: '',
      },
      {
        id: 4,
        name: 'Рябчик',
        nameLatin: 'Bonasa bonasia',
        band: 'Курообразные',
        bandLatin: 'Galliiformes',
        family: 'Тетеревиные',
        familyLatin: 'Tetraonidae',
        description: 'Обычный гнездящийся оседлый вид. Распространен широко, но неравномерно. В северных районах численность его несколько выше, чем в южных.',
        weight: 'самцы 310-390 г, самки 311-387 г',
        length: '32-40 см',
        wingspan: '54-64 см',
        image: '',
        audio: '',
      },
      {
        id: 5,
        name: 'Тетерев',
        nameLatin: 'Lyrix tetrix',
        band: 'Курообразные',
        bandLatin: 'Galliiformes',
        family: 'Тетеревиные',
        familyLatin: 'Tetraonidae',
        description: 'Обычный немногочисленный гнездящийся оседлый вид, популярный объект спортивной охоты. Распространен широко, но неравномерно. Чаще встречается в северо-восточных районах республики и в центральной части Полесья.',
        weight: 'самцы 1,0-1,6 кг, самки 0,7-1,1 кг',
        length: 'самцы 51-71 см, самки 41-51 см',
        wingspan: 'самцы 81-100, самки 66-80 см',
        image: '',
        audio: '',
      },
      {
        id: 6,
        name: 'Фазан',
        nameLatin: 'Phasianus colchicus',
        band: 'Курообразные',
        bandLatin: 'Galliiformes',
        family: 'Фазановые',
        familyLatin: 'Phasianidae',
        description: 'Территория Беларуси не входит в состав естественного ареала данного вида. Очень редкий вид, интродуцированный на крайнем юго-западе Беларуси. Здесь изредка гнездятся фазаны популяций.',
        weight: 'самцы 0,7-2,0 кг, самки 0,65-1,6 кг',
        length: 'самцы 71-83 см, самки 59-70 см',
        wingspan: 'самцы 75-80, самки 66-70 см',
        image: '',
        audio: '',
      }
    ],
    [
      {
        id: 1,
        name: 'Ворон',
        nameLatin: 'Corvus corax',
        band: 'Воробьинообразные',
        bandLatin: 'Passeriformes',
        family: 'Врановые',
        familyLatin: 'Corvidae',
        description: 'Обычный гнездящийся оседлый вид. Распространен повсеместно, обычен на всей территории, а в местах расположения крупных животноводческих комплексов со скотомогильниками бывает многочислен.',
        weight: 'самцы 1,1-1,56 кг, самки 0,8-1,32 кг',
        length: '60-67 см',
        wingspan: '115-150 см',
        image: '',
        audio: '',
      },
      {
        id: 2,
        name: 'Чиж',
        nameLatin: 'Carduelis spinus',
        band: 'Воробьинообразные',
        bandLatin: 'Passeriformes',
        family: 'Вьюрковые',
        familyLatin: 'Fringillidae',
        description: 'Обычный гнездящийся, кочующий, пролетный и зимующий вид. Обычен, но немногочислен на гнездовье. Южная граница его ареала в Европейской части приблизительно совпадает с южной границей произрастания ели.',
        weight: 'самцы 10-17 г, самки 9-16 г',
        length: '11-12,5 см',
        wingspan: '20-23 см',
        image: '',
        audio: '',
      },
      {
        id: 3,
        name: 'Жаворонок полевой',
        nameLatin: 'Alauda arvensis',
        band: 'Воробьинообразные',
        bandLatin: 'Passeriformes',
        family: 'Жаворонковые',
        familyLatin: 'Alaudidae',
        description: 'Обычный гнездящийся, перелетный и транзитно мигрирующий вид. Местами многочислен, широко распространен на всей территории Беларуси.',
        weight: 'самцы 28-46 г, самки 26-46 г',
        length: '17-20,5 см',
        wingspan: '30-38 см',
        image: '',
        audio: '',
      },
      {
        id: 4,
        name: 'Ласточка городская',
        nameLatin: 'Delichon urbica',
        band: 'Воробьинообразные',
        bandLatin: 'Passeriformes',
        family: 'Ласточковые',
        familyLatin: 'Hirundidae',
        description: 'Обычный гнездящийся перелетный и транзитно мигрирующий вид, однако распространен далеко не повсеместно.',
        weight: 'самцы 16-22 г, самки 19-24 г',
        length: '13-16 см',
        wingspan: '26-32 см',
        image: '',
        audio: '',
      },
      {
        id: 5,
        name: 'Свиристель',
        nameLatin: 'Bombycilla garrulus',
        band: 'Воробьинообразные',
        bandLatin: 'Passeriformes',
        family: 'Свиристелевые',
        familyLatin: 'Bombycillidae',
        description: 'Обычный пролетный и зимующий вид. Птица размером со скворца, с пушистым буровато-серым оперением, на нижней стороне имеющим винно-красный оттенок.',
        weight: 'самцы 54-73 г, самки 67-73 г',
        length: '18-21 см',
        wingspan: '32-35,5 см',
        image: '',
        audio: '',
      },
      {
        id: 6,
        name: 'Иволга',
        nameLatin: 'Oriolus oriolus',
        band: 'Воробьинообразные',
        bandLatin: 'Passeriformes',
        family: 'Иволговые',
        familyLatin: 'Oriolidae',
        description: 'Обычный, широко распространенный гнездящийся перелетный и транзитно мигрирующий вид. Несколько крупнее скворца, одна из наиболее ярко окрашенных птиц нашей фауны.',
        weight: 'самцы 50-87 г, самки 51-85 г',
        length: '23,5-25 см',
        wingspan: '44-47 см',
        image: '',
        audio: '',
      }
    ],
    [
      {
        id: 1,
        name: 'Чибис',
        nameLatin: 'Vanellus vanellus',
        band: 'Ржанкообразные',
        bandLatin: 'Charadiiformes',
        family: 'Ржанковые',
        familyLatin: 'Charadriidae',
        description: 'Обычный гнездящийся перелетный и транзитно мигрирующий, широко распространен на территории республики вид. Из всех куликов наиболее многочисленный.',
        weight: 'самцы 191-230 г, самки 180-257 г',
        length: '28-34 см',
        wingspan: '66-80 см',
        image: '',
        audio: '',
      },
      {
        id: 2,
        name: 'Дупель',
        nameLatin: 'Gallinago media',
        band: 'Ржанкообразные',
        bandLatin: 'Charadiiformes',
        family: 'Бекасовые',
        familyLatin: 'Scolopacidae',
        description: 'Малочисленный гнездящийся перелетный и транзитно мигрирующий вид, лишь местами обычный. Распространен на всей территории, но более обычен на Полесье. Встречается изолированными группировками.',
        weight: 'самцы 130-205 г, самки 160-230 г',
        length: '24,5-31 см',
        wingspan: '43-48 см',
        image: '',
        audio: '',
      },
      {
        id: 3,
        name: 'Клуша',
        nameLatin: 'Larus fuscus',
        band: 'Ржанкообразные',
        bandLatin: 'Charadiiformes',
        family: 'Чайковые',
        familyLatin: 'Laridae',
        description: 'Малочисленный транзитно мигрирующий вид. В Беларуси встречается в основном во время миграций в весенние (апрель - май) и осенние (сентябрь - ноябрь) месяцы.',
        weight: 'самцы 730-1180 г, самки 560-770 г',
        length: '52-64 см',
        wingspan: '120-150 см',
        image: '',
        audio: '',
      },
      {
        id: 4,
        name: 'Травник',
        nameLatin: 'Tringa totanus',
        band: 'Ржанкообразные',
        bandLatin: 'Charadiiformes',
        family: 'Бекасовые',
        familyLatin: 'Scolopacidae',
        description: 'Обычный гнездящийся перелетный и транзитно мигрирующий вид. Один из наиболее широко распространенных видов куликов, везде обычен, но более многочислен в изобилующем болотными угодьями Полесье.',
        weight: 'самцы 90-149 г, самки 102-120 г',
        length: '27-31 см',
        wingspan: '50-65 см',
        image: '',
        audio: '',
      },
      {
        id: 5,
        name: 'Чернозобик',
        nameLatin: 'Calidris alpina',
        band: 'Ржанкообразные',
        bandLatin: 'Charadiiformes',
        family: 'Бекасовые',
        familyLatin: 'Scolopacidae',
        description: 'Очень редкий гнездящийся (на севере Беларуси в Поозерье) и довольно обычный транзитно мигрирующий вид. Включен в «Красную книгу Республики Беларусь».',
        weight: 'самцы 44,5-57,4 г, самки 45,6-56,5 г',
        length: '19,5-23 см',
        wingspan: '35.5-41 см',
        image: '',
        audio: '',
      },
      {
        id: 6,
        name: 'Зуёк малый',
        nameLatin: 'Charadrius dubius',
        band: 'Ржанкообразные',
        bandLatin: 'Charadiiformes',
        family: 'Ржанковые',
        familyLatin: 'Charadriidae',
        description: 'Обычный, повсеместно распространенный на территории республики, гнездящийся перелетный и транзитно мигрирующий вид.',
        weight: 'самцы 31,5-38 г, самки 35,6-46,5 г',
        length: '16-19 см',
        wingspan: '35,5-38,5 см',
        image: '',
        audio: '',
      }
    ],
    [
      {
        id: 1,
        name: 'Беркут',
        nameLatin: 'Aquila chrysaetus',
        band: 'Хищные',
        bandLatin: 'Falconiformes',
        family: 'Ястребиные',
        familyLatin: 'Accipitridae',
        description: 'Очень редкий гнездящийся (в основном на севере республики и преимущественно в Витебской обл.) и зимующий вид. В настоящее время на гнездовании найден только на верховых болотах Белорусского Поозерья.',
        weight: 'самцы 2,8-4,5 кг, самки 3,8-5,8 кг',
        length: 'самцы 82-91 см, самки 89-102 см',
        wingspan: '175-220 см',
        image: '',
        audio: '',
      },
      {
        id: 2,
        name: 'Змееяд',
        nameLatin: 'Circaetus gallicus',
        band: 'Хищные',
        bandLatin: 'Falconiformes',
        family: 'Ястребиные',
        familyLatin: 'Accipitridae',
        description: 'Редкий гнездящийся перелетный вид. На территории республики распространен крайне неравномерно: большинство находок гнезд отмечается в районах Полесья и Поозерья.',
        weight: 'самцы 1.4-1.65 кг, самки 1.6-1.8 кг',
        length: '62-75 см',
        wingspan: '160-180 см',
        image: '',
        audio: '',
      },
      {
        id: 3,
        name: 'Скопа',
        nameLatin: 'Pandion haliaetus',
        band: 'Хищные',
        bandLatin: 'Falconiformes',
        family: 'Скопиные',
        familyLatin: 'Pandionidae',
        description: 'Редкий гнездящийся перелетный и транзитно мигрирующий вид. Распространена широко, но неравномерно; в Поозерье встречается несколько чаще, чем на остальной территории.',
        weight: 'самцы 1,25-1,52 кг, самки 1,5-2,1 кг',
        length: '56-62 см',
        wingspan: '147-169 см',
        image: '',
        audio: '',
      },
      {
        id: 4,
        name: 'Осоед',
        nameLatin: 'Pernis apivorus',
        band: 'Хищные',
        bandLatin: 'Falconiformes',
        family: 'Ястребиные',
        familyLatin: 'Accipitridae',
        description: 'Широко распространен, но немногочислен. Обычный гнездящийся, перелетный и транзитно мигрирующий вид. Из-за скрытного образа жизни производит впечатление довольно редкой птицы.',
        weight: 'самцы 580-896 г, самки 810-1105 г',
        length: '58-62 см',
        wingspan: '115-135 см',
        image: '',
        audio: '',
      },
      {
        id: 5,
        name: 'Канюк',
        nameLatin: 'Buteo buteo',
        band: 'Хищные',
        bandLatin: 'Falconiformes',
        family: 'Ястребиные',
        familyLatin: 'Accipitridae',
        description: 'Самая обычная из хищных птиц нашей фауны. Наиболее многочисленный и широко распространенный вид Белорусского Поозерья. Гнездящийся, перелетный и транзитно мигрирующий.',
        weight: 'самцы 540-790 г, самки 710-1270 г',
        length: '45-57 см',
        wingspan: '101-128 см',
        image: '',
        audio: '',
      },
      {
        id: 6,
        name: 'Чеглок',
        nameLatin: 'Falco subbuteo',
        band: 'Хищные',
        bandLatin: 'Falconiformes',
        family: 'Соколиные',
        familyLatin: 'Falconidae',
        description: 'Перелетный гнездящийся и транзитно мигрирующий вид, никогда не зимует. В Беларуси, пожалуй, самый обычный из соколов, хотя в целом немногочисленная птица.',
        weight: 'самцы 165-208 г, самки 226-312 г',
        length: '29-37 см',
        wingspan: '72-84 см',
        image: '',
        audio: '',
      }
    ],










    [
      {
        id: 1,
        name: 'Воробей',
        species: 'Passer domesticus',
        description: 'Воробьи являются самыми известными и узнаваемыми пернатыми. Их легко узнать по пестрому оперению и задорному чириканью. Воробьи относятся к синатропному виду — они селятся поблизости к человеческому жилищу.',
        image: 'https://live.staticflickr.com//65535//49366595303_06cf65b07e.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/CXFHOPIVAS/XC503224-191020_0134.mp3'
      },
      {
        id: 2,
        name: 'Грач',
        species: 'Corvus frugilegus',
        description: 'Грачи очень умные и сообразительные птицы. С помощью клюва они создают и используют простейшие орудия. У грачей развит рефлекс на звуки трактора. Услышав «тарахтение», они летят на звук – трактор пашет землю, значит, в этом месте много корма.',
        image: 'https://live.staticflickr.com//65535//49347123322_291c86b016.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/RLRHCUIPIY/XC512540-gawron%20Suble%2019.12.19%20%2012.35.mp3'
      },
      {
        id: 3,
        name: 'Галка',
        species: 'Coloeus monedula',
        description: 'Слово «галка» произошло из старославянского языка и переводится как «чёрный». Этим словом часто называют воронов или других черных птиц. Латинское название галки «monedula» связывают со словами монета за любовь птицы к блестящим и ярким вещам.',
        image: 'https://live.staticflickr.com//65535//49237149586_993cf685c5.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/GYAUIPUVNM/XC510498-Coloeus%20monedula_2019.11.13_11.55_01.mp3'
      },
      {
        id: 4,
        name: 'Певчий дрозд',
        species: 'Turdus philomelos',
        description: 'Дрозд — лучший певец из отряда воробьиных. Песня состоит только из красивых звучных свистов и коротких трелей. Чаще всего её можно услышать в утреннее и вечернее время. Поют дрозды в течении всего периода гнездования.',
        image: 'https://live.staticflickr.com/65535/48979125763_e2534f54bd.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/BLMSIUFTFU/XC513326-190704_1146_TF-Glogow.mp3'
      },
      {
        id: 5,
        name: 'Сорока',
        species: 'Pica pica',
        description: 'Сорока очень трудолюбивая птица. Она строит до восьми гнёзд, а потом выбирает из них самое лучшее. Вход в гнездо сорок всегда обращен на юг, чтобы в жилище было теплее. Сороки являются единственными птицами, которые узнают себя в зеркале.',
        image: 'https://live.staticflickr.com//65535//49360363066_ff02bb6a73.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/GYAUIPUVNM/XC500868-Pica%20pica2019.08.23_09.18_02.mp3'
      },
      {
        id: 6,
        name: 'Сойка',
        species: 'Garrulus glandarius',
        description: 'Когда сойка волнуется, хохолок на её голове взъерошивается. Птица старается создать устрашающее зрелище. Сойки умеют имитировать голоса других птиц, животных и звуки, которые создает человек. На зиму они делают большие запасы желудей и орехов.',
        image: 'https://live.staticflickr.com//65535//49369678956_9a7465c7f4.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/TFOGOENSTQ/XC501517-191008_1590%201300.%20Eichelh%C3%A4her%20D%2C%20NW%2C%20LEV.%20Stephan%20Risch.mp3'
      }
    ],
    [
      {
        id: 1,
        name: 'Зяблик',
        species: 'Fringilla coelebs',
        description: 'В дикой природе насчитывается 450 видов зябликов. Зимой зяблики ведут стайный образ жизни. Иногда в их семьях можно увидеть воробьев. Запевают зяблики весной, с наступлением брачного периода. Их пение – это заливистые многоминутные рулады.',
        image: 'https://live.staticflickr.com/65535/49143150817_2d3a2f6c1e.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/ZNCDXTUOFL/XC512407-150622_03%20zi%C4%99ba%20%282%29.mp3'
      },
      {
        id: 2,
        name: 'Клёст',
        species: 'Loxia curvirostra',
        description: 'Клестов называют «рождественскими» птицами. В естественных условиях они дают потомство зимой – в январе. Эти птицы утепляют свои гнезда мхом и шерстью животных, потому птенцам не холодно. В поисках шишек клесты могут улетать за 3500 км от гнезда.',
        image: 'https://live.staticflickr.com//65535//49365470123_f2de66bb35.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/OTVUCEGYZN/XC495381-Kruisbek%20roep%20NHD%20290619.mp3'
      },
      {
        id: 3,
        name: 'Горлица',
        species: 'Streptopelia turtur',
        description: 'Горлица обитает в смешанных и широколиственных лесах, а также в городских парках и поселках. Птицы часто выбирают места жизни рядом с человеком и легко привыкают к людям. Благодаря мелодичному приятному пению горлиц часто разводят в домашних условиях.',
        image: 'https://live.staticflickr.com/65535/48063004977_84252f9ceb.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/ZNCDXTUOFL/XC324106-Turkawka_Streptopelia_turtur_Poland_Jarek_Matusiak_2011625_07.mp3'
      },
      {
        id: 4,
        name: 'Дятел',
        species: 'Dendrocopos major',
        description: 'Дятел – заметная и шумная птица, часто живет рядом с человеком. С середины января до конца июня можно услышать «барабанную дробь» дятлов – трель от вибрации веток под быстрыми ударами клюва птицы. В хорошую погоду дробь слышна в радиусе 1,5 км.',
        image: 'https://live.staticflickr.com/65535/49339376578_e933426455.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/ZNCDXTUOFL/XC518928-AB-017%20dzi%C4%99cio%C5%82%20du%C5%BCy%20agresja%20%282%29.mp3'
      },
      {
        id: 5,
        name: 'Удод',
        species: 'Upupa epops',
        description: 'Удоды предпочитают жить на открытых ландшафтах с отдельными деревьями или рощами. Наиболее удобными для птицы являются лесостепь и саванна. Удод может выбирать места жительства рядом с человеком: пастбища, виноградники, фруктовые сады.',
        image: 'https://live.staticflickr.com//65535//49226383598_6f8be86a06.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/ZNCDXTUOFL/XC477326-dudek%20%282%29.mp3'
      },
      {
        id: 6,
        name: 'Стриж',
        species: 'Apus apus',
        description: 'Стрижа можно увидеть практически в каждом уголке планеты. Они обитают как в лесных зонах, так и на открытых местностях. Живут стрижи крупными стаями. Большие колонии этих птиц можно увидеть в городах или на прибрежных скалах.',
        image: 'https://live.staticflickr.com//65535//48386150031_7b749df74b.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/TMUAWSDHDJ/XC511871-G.mp3'
      }
    ],
    [
      {
        id: 1,
        name: 'Жаворонок',
        species: 'Alauda arvensis',
        description: 'Жаворонки — перелетные птицы. С начала сентября они отлетают на юг. Возвращаются они в начале марта, независимо от того, сошел снег или нет. По прилету жаворонков определяли наступление весны и пору, когда пора пахать землю.',
        image: 'https://live.staticflickr.com/65535/47105096764_f751fba568.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/ZNCDXTUOFL/XC462158-Skowronek_Alauda_arvensis_Poland_Jarek_Matusiak_%20-006%20skowronek%20%282%29.mp3'
      },
      {
        id: 2,
        name: 'Соловей',
        species: 'Luscinia luscinia',
        description: 'Соловьи поют с начала мая и до конца лета. Каждая песня соловья состоит из 12 повторяющихся элементов, которые еще называют коленами. Кроме собственных трелей, соловьи легко и хорошо перенимают пение других птиц.',
        image: 'https://live.staticflickr.com/7605/27669397735_f3c21758f2.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/HILVWSADVL/XC513809-R07_0052%20Thrush%20Nightingale%20Snipe.mp3'
      },
      {
        id: 3,
        name: 'Скворец',
        species: 'Sturnus vulgaris',
        description: 'Скворцы - перелётные птицы. Синхронный перелет больших стай скворцов называется мурмурацией. Это красивое и завораживающее явление – множество птиц будто танцуют в воздухе, образуя замысловатые фигуры, которые уменьшаются и увеличиваются в небе.',
        image: 'https://live.staticflickr.com/65535/49357593971_9509fe1d7c.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/GYAUIPUVNM/XC515519-2020.01.01_17.24_01.MP3'
      },
      {
        id: 4,
        name: 'Иволга',
        species: 'Oriolus oriolus',
        description: 'Мелодичность голоса иволги сравнивают со звучанием флейты. Человеку сложно разглядеть иволгу, так как она обитает высоко на деревьях. Иволга не только очень красивая, но и  полезная птица. Она уничтожает ядовитых гусениц, которых не поедают другие птицы.',
        image: 'https://live.staticflickr.com/65535/47102184004_58a93380b9.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/GYAUIPUVNM/XC491801-2019.07.07_06.28_01.mp3'
      },
      {
        id: 5,
        name: 'Свиристель',
        species: 'Bombycilla garrulus',
        description: 'У свиристели очень цепкие коготки, что помогает птице удерживаться на ветках и склевывать ягоды, которые труднее всего достать. В период ухаживаний самец предлагает самке ягоду или другое угощение. Если самка его принимает, то птицы создают пару.',
        image: 'https://live.staticflickr.com//65535//49367433842_1b06da0e6b.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/ZNCDXTUOFL/XC517421-AB-004%20%282%29%20jemio%C5%82uszka.mp3'
      },
      {
        id: 6,
        name: 'Щегол',
        species: 'Carduelis carduelis',
        description: 'Щеглы поют красиво и мелодично. И в природе, и в неволе они щебечут почти круглый год. В пении щегла различают более 20 переливчатых трелей. Щеглы привыкают к людям, и даже могут возвратиться к хозяину после того, как их выпустили на волю',
        image: 'https://live.staticflickr.com//65535//49366257253_db3ce48b9a.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/VOLIQOYWKG/XC489265-190724_07.58h_putter_biesbosch_%20boompjes%20langs%20open%20water_zang_1ex_ad_niet%20gezien_.mp3'
      }
    ],
    [
      {
        id: 1,
        name: 'Орёл',
        species: 'Aquila nipalensis',
        description: 'В древние времена орел был символом солнца. Орлы часто парят над землей, при этом скорость их перемещения может достигать 240 км/ч. Иллюзия медленного движения происходит из-за высоты полета – более 700 метров',
        image: 'https://live.staticflickr.com//4835//43867392960_7105d71e19.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/KTBTZAHSXF/10_Aquila_nipalensis_al02D85.mp3'
      },
      {
        id: 2,
        name: 'Коршун',
        species: 'Milvus migrans',
        description: 'Коршуны – крупные хищники, в высоту они достигают около полуметра, а вес взрослых особей достигает 1 кг. Крылья узкие и длинные, их размах составляет 1,5 м. Коршуны часто гнездятся большими стаями и даже образуют крупные колонии.',
        image: 'https://live.staticflickr.com//65535//48701190276_ee2a9ed594.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/SDPCHKOHRH/XC485740-2019-06-22%20Selenga%20Milan%20brun%20cris%20de%20quemandage%203.mp3'
      },
      {
        id: 3,
        name: 'Лунь',
        species: 'Circus cyaneus',
        description: 'Лунь – это небольшой сокол. Питается в основном мышевидными грызунами, основа его рациона – полёвки, хомяки, мыши. Оперение луня может быть пепельно-серым. С такой птицей связано сравнение «седой, как лунь».',
        image: 'https://live.staticflickr.com/4480/37240531151_b74619c99d.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/BLMSIUFTFU/XC513498-190709_1175_Cir.cyan-f.mp3'
      },
      {
        id: 4,
        name: 'Сокол',
        species: 'Falco peregrinus',
        description: 'Латинское название сокола Falco произошло от слова «серп» из-за серповидной формы крыльев. Длинные и широкие крылья позволяют соколу высоко подниматься в небо и свободно парить. Скорость полёта сокола достигает 280-320 километров в час.',
        image: 'https://live.staticflickr.com//65535//49310710607_92a3a145a9.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/MMEJYLOPDO/XC496049-Pilgrimsfalk_06.mp3'
      },
      {
        id: 5,
        name: 'Ястреб',
        species: 'Accipiter gentilis',
        description: 'Для всех ястребов характерны широкие и короткие крылья. Ещё один отличительный признак - белые «брови» над глазами. Славянские дружинники размещали изображение ястреба на своих знаменах, как символ отваги, мощи и безжалостности к врагам.',
        image: 'https://live.staticflickr.com//65535//49024617331_b9d0d2c9b3.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/MMEJYLOPDO/XC512740-Duvh%C3%B6k_09.mp3'
      },
      {
        id: 6,
        name: 'Филин',
        species: 'Bubo bubo',
        description: 'Полет филина бесшумный, зрение очень острое. Эти особенности делают птицу непревзойденным ночным охотником. У филина нет естественных врагов, ни один зверь не охотится на взрослых птиц. А вот на птенцов нападают лисы и волки.',
        image: 'https://live.staticflickr.com/65535/48137123012_393653c2e4.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/WNLIDKJKXT/XC518386-sense%20t%C3%ADtol.mp3'
      }
    ],
    [
      {
        id: 1,
        name: 'Альбатрос',
        species: 'Diomedea exulans',
        description: 'Альбатрос - самая крупная летающая птица в мире. Размах крыльев достигает три с половиной, вес - десять килограммов. Большую часть жизни альбатросы проводят в воздухе, покрывая над океанскими просторами огромные расстояния',
        image: 'https://live.staticflickr.com/7557/16260253965_8e9430cb66.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/WOEAFQRMUD/XC293087-Diomedea%20exulans151120_T254.mp3'
      },
      {
        id: 2,
        name: 'Олуша',
        species: 'Sula nebouxii',
        description: 'Особенностью голубоногой олуши является не только насыщенный ярко-синий цвет лапок, но еще и тот факт, что они очень теплые. В то время как другие виды птиц греют кладки своим телом, голубоногая олуша делает это с помощью лапок',
        image: 'https://live.staticflickr.com/800/40645471394_4422e69ed8.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/YHKQPPJDVP/XC411507-171217_1491%20BF%20Booby%205ft%20IDLP%201230%20mp3%20amp.mp3'
      },    
      {
        id: 3,
        name: 'Буревестник',
        species: 'Puffinus griseus',
        description: 'Размеры буревестниковых разные. Самые маленькие из них в длину составляют до 25 см, самые большие - до 1 м, при размахе крыльев около 2 м. Существует поверье, что появление буревестника в воздухе предвещает бурю, о чем говорит само название птицы.',
        image: 'https://live.staticflickr.com//607//22136056020_935cb113f9.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/XQEVNREHJY/SHEARWATER%20Christmas%20Island_04_Motu_Isla%20de%20Pascua-Easter%20Island_CH_4MAR03_Alvaro%20Jaramillo.mp3'
      },
      {
        id: 4,
        name: 'Пеликан',
        species: 'Pelecanus',
        description: 'Пеликаны — обитатели морей и рек. Ходят они неуклюже, но хорошо летают и плавают. Питаются в основном рыбой, устраивают коллективные охоты — выстроившись полукругом хлопают по воде крыльями и клювами и вытесняют напуганную рыбу на мелководье.',
        image: 'https://live.staticflickr.com/65535/49159147156_dcbbb5c12a.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/XAMHIHFTZG/XC331138-call1.mp3'
      },
      {
        id: 5,
        name: 'Пингвин',
        species: 'Aptenodytes forsteri',
        description: 'Самец императорского пингвина достигает роста 130 см, его масса может приближаться к 50 кг. Из всех современных пингвинов этот вид – самый крупный. Питание пингвина состоит из рыбы, кальмаров и криля. Охотятся птицы в океане большими группами.',
        image: 'https://live.staticflickr.com/5202/5252413926_8e013a3efd.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/OOECIWCSWV/XC449827-LS100829%20King%20Penguin%20call%20A.mp3'
      },
      {
        id: 6,
        name: 'Чайка',
        species: 'Larus argentatus',
        description: 'Чайки населяют берега морей, озёр, рек, водохранилищ, болот, часто гнездятся на островах. С конца прошлого века чайки стали появляться в крупных городах, где устраивает гнёзда на крышах зданий. Все чайки ведут колониальный образ жизни.',
        image: 'https://live.staticflickr.com/65535/48577115317_7034201dde.jpg',
        audio: 'https://www.xeno-canto.org/sounds/uploaded/VOLIQOYWKG/XC501190-190801_06.50h_zilvermeeuw_duinen%20van%20goeree_roep_2ex_overvliegend_gezien_.mp3'
      }
    ]
];


const category = [
    'Аистообразные',
    'Гусеобразные',
    'Курообразные',
    'Воробьинообразные',
    'Ржанкообразные',
    'Хищные',
];

export { data, category };
